// <auto-generated />
using BuffetAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuffetAPI.Migrations
{
    [DbContext(typeof(BuffetAPIContext))]
    [Migration("20241203192946_plat")]
    partial class plat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuffetAPI.Plat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Biscuit Double gingembre"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Biscuit Brisures de chocolat"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Biscuit Amaretti"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Biscuit S'mores au beurre noisette"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Biscuit Canneberges"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
