// <auto-generated />
using System;
using BuffetAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuffetAPI.Migrations
{
    [DbContext(typeof(BuffetAPIContext))]
    partial class BuffetAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuffetAPI.Data.Plat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Mange")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Prix")
                        .HasColumnType("float");

                    b.Property<int>("TypePlatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypePlatId");

                    b.ToTable("Plat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mange = false,
                            Nom = "Biscuit Double gingembre",
                            Prix = 2.25,
                            TypePlatId = 3
                        },
                        new
                        {
                            Id = 2,
                            Mange = false,
                            Nom = "Biscuit Brisures de chocolat",
                            Prix = 2.25,
                            TypePlatId = 3
                        },
                        new
                        {
                            Id = 3,
                            Mange = false,
                            Nom = "Biscuit Amaretti",
                            Prix = 2.25,
                            TypePlatId = 3
                        },
                        new
                        {
                            Id = 4,
                            Mange = false,
                            Nom = "Biscuit S'mores au beurre noisette",
                            Prix = 2.25,
                            TypePlatId = 3
                        },
                        new
                        {
                            Id = 5,
                            Mange = false,
                            Nom = "Biscuit Canneberges",
                            Prix = 2.25,
                            TypePlatId = 3
                        });
                });

            modelBuilder.Entity("BuffetAPI.Data.TypePlat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypePlat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Végétarien"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Carnivore"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Sucrerie"
                        });
                });

            modelBuilder.Entity("BuffetAPI.Data.Plat", b =>
                {
                    b.HasOne("BuffetAPI.Data.TypePlat", "TypePlat")
                        .WithMany()
                        .HasForeignKey("TypePlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypePlat");
                });
#pragma warning restore 612, 618
        }
    }
}
